mybatis: 
    configuration:  #Mybatis配置
        default-statement-timeout: 30

spring: 
    cache: 
        cache-names: sysCache,paramCache
        caffeine:
            spec: maximumSize=500,expireAfterAccess=600s
#    liquibase: 
#        enabled: true
            
flowable: 
    #database-schema-update: true
    idm: 
        enabled: false
