logging: 
    level: 
        root: INFO
        org.eap: DEBUG
        org.springframework: INFO
        
        
spring: 
    profiles: 
        include: framework,framework-web
    datasource: 
        druid: 
            url: jdbc:mysql://localhost:3306/erpnext?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
            username: root
            password: Hch_2008
            driver-class-name: com.mysql.cj.jdbc.Driver
            initial-size: 5
            max-active: 50
            min-idle: 5
            min-evictable-idle-time-milli: 100000
            time-between-eviction-runs-millis: 60000

eap: 
    defaultPassword: Aa0123!